version: '3.7'

services:
# ---------------------- DATABASE ----------------------

# UserDB
  db-user:
    image: mysql:9.0
    environment:
      MYSQL_DATABASE: db_user
      MYSQL_USER: user123
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: RootPassword
    restart: unless-stopped
    ports:
      - 3307:3306
    expose:
      - 3306
  # CommentDB
  db-comment:
    image: mysql:9.0
    environment:
      MYSQL_DATABASE: db_comment
      MYSQL_USER: user123
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: RootPassword
    restart: unless-stopped
    ports:
      - 3305:3306
  # ---------------------- MONGODB ----------------------
  # NotificationDB
  db-notification:
    image: mongo:8.0.3-noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27019:27017
    volumes:
      - mongodb_data_notification:/data/db

  # PostServiceDB
  db-blogPost:
    image: mysql:9.0
    environment:
      MYSQL_DATABASE: db_blogPost
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: RootPassword
    ports:
      - 3308:3306

    restart: unless-stopped
  # ---------------------- KAFKA CONFIG ----------------------
# Zookeeper
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

# Kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

# ---------------------- KEYCLOAK ----------------------

# Keycloak
  keycloak:
    image: keycloak/keycloak:23.0.7
    command:
      - start-dev
      -  --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - /home/keycloak/realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - "9090:8080"
volumes:
  mongodb_data_notification:
  mongodb_data_blogPost: