spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/demo/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/demo
        registration:
          spring-with-test-scope:
            provider: keycloak
            client-id: spring-with-test-scope
            client-secret: uR7wUJrWcg79eBI6dBJKZR0u0PFa9ydo
            authorization-grant-type: authorization_code
            scope: openid
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive

  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: USERSERVICE
          uri: lb://UserService
          predicates:
            - Path=/authUser/**, /preferences/**
        - id: POSTSERVICE
          uri: lb://PostService
          predicates:
            - Path=/blogPost/**, /likes/**
        - id: COMMENT-SERVICE
          uri: lb://CommentsService/**
          predicates:
            - Path=/comment/**
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /test-service/v3/api-docs
        name: Test Service
      - url: /blogPost/v3/api-docs
        name: Post Service
      - url: /comment/v3/api-docs
        name: Comment Service
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8181