spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/demo/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/demo
        registration:
          spring-with-test-scope:
            provider: keycloak
            client-id: spring-with-test-scope
            client-secret: uR7wUJrWcg79eBI6dBJKZR0u0PFa9ydo
            authorization-grant-type: authorization_code
            scope: openid
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive

  cloud:
    gateway:
      default-filters:
        - TokenRelay=

      routes:
        - id: USERSERVICE
          uri: lb://UserService
          predicates:
            - Path=/authUser/**
        - id: POSTSERVICE
          uri: lb://PostService
          predicates:
            - Path=/blogPost/**
        - id: COMMENT-SERVICE
          uri: lb://CommentsService/**
          predicates:
            - Path=/comment/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8181